version: '3.8'

services:
  tager-tech:
    container_name: tager-tech
    build: .
    volumes:
      - ./tager-tech:/var/www/html
    ports:
      - 9000:9000 # Mapping the correct port
    depends_on:
      - mysql_db

  nginx:
    image: nginx:1.26-alpine
    container_name: laravel_nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tager-tech

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taravel_docker
    ports:
      - 3307:3306

  # postgres_db:
  #   image: postgres:latest
  #   shm_size: 128mb
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
